### ISSUE TITLE
Interaction BDD

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#10]
Je n'arrive plus à sauvegarder mes réponses, ni à enregistrer la modification/suppression d'éléments sur certains exercices (b213, b218)
Le bouton "passer à la suite" sur l'écran de réponse ne semble pas déclencher quoi que ce soit

**Comment by haniju** [comment]
Du coup ça m'empeche d'afficher l'écran réponse b233 par exemple...
Peut-etre qu'il faudrait que je reparte à 0 sur un autre profil ?

**Comment by haniju** [comment]
Ok, donc je viens de mettre à jour la BDD (je n'avais pas vu ton message sur le ggchat)
L'import est terminé, mais j'ai eu un message d'erreur : 
Error
SQL query:
INSERT INTO `bma3_bma_questions` (`ID`, `PARENT_ID`, `level_1`, `level_2`, `level_3`, `level_4`, `display_order`, `category`, `name`, `field`, `type`, `html_display`, `parent_type`, `title`, `question`, `explication`, `placeholder`, `star_min_label`, `star_max_label`, `label_before`, `other`, `creation_date`) 
VALUES (NULL, NULL, '0', '0', '0', '0', '0', 'B218', 'B218-description', 'description', 'textarea', NULL, '', '', 'Décrivez la nature de la transaction pour passer de l’opération X à l’opération Y', '', '', '', '', '', '0', '2017-09-04 20:11:21')
MySQL said: #1054 - Unknown column 'level_4' in 'field list'

**Comment by soulmakh** [comment]
Je viens de mettre à jour le fichier update_3.sql
Essaie de l'importer à nouveau, et tiens moi au courant.
Désolé pour le retard

**Comment by haniju** [comment]
Hello Said, je ne vois pas de trace d'update du fichier update_3.sql
https://github.com/booosterdemobilite/bma-sequence-manager/tree/master/sql
Est-ce que tu as push ?

**Comment by soulmakh** [comment]
Je viens de faire le push :)
désolé

**Comment by haniju** [comment]
Error
SQL query:

ALTER TABLE `bma3_bma_operations` ADD `description` VARCHAR(300) NOT NULL AFTER `display_order

MySQL said: Documentation

#1046 - No database selected

**Comment by haniju** [comment]
Je n'arrive plus à ouvrir b223, meme en mode exercice...
J'ai ce message d'erreur dans la console du navigateur : 
TypeError: Cannot read property 'push' of undefined
    at exob223.js:55
    at angular.min.js:134
    at m.$digest (angular.min.js:145)
    at m.$apply (angular.min.js:149)
    at l (angular.min.js:102)
    at XMLHttpRequest.A.onload (angular.min.js:107) "Possibly unhandled rejection: {}"
(anonymous) @ angular.min.js:123
(anonymous) @ angular.min.js:95
g @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
l @ angular.min.js:102
A.onload @ angular.min.js:107
XMLHttpRequest.send (async)
(anonymous) @ angular.min.js:108
p @ angular.min.js:103
(anonymous) @ angular.min.js:101
(anonymous) @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
l @ angular.min.js:102
A.onload @ angular.min.js:107
XMLHttpRequest.send (async)
(anonymous) @ angular.min.js:108
p @ angular.min.js:103
(anonymous) @ angular.min.js:101
(anonymous) @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
_updateScopeInfo @ plateau.js:287
(anonymous) @ ?exo_key=exob223:126
setTimeout (async)
(anonymous) @ ?exo_key=exob223:125
