### ISSUE TITLE
bug d'affichage b233

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#17]
Le 233 ne se charge plus chez moi...

Dans la console : 
http://errors.angularjs.org/1.6.4/$http/baddata?p0=%5B%7B%22id%22%3A%221%22%2C%22parent_id%22%3Anull%2C%.......ça continue comme ça très longtemps.......%5Cfunctions.php%3C%2Fb%3E%20on%20line%20%3Cb%3E3720%3C%2Fb%3E%3Cbr%20%2F%3E%0A&p1=%7B%7D
    at angular.min.js:6
    at nc (angular.min.js:96)
    at angular.min.js:97
    at q (angular.min.js:7)
    at xd (angular.min.js:97)
    at f (angular.min.js:99)
    at angular.min.js:134
    at m.$digest (angular.min.js:145)
    at m.$apply (angular.min.js:149)
    at l (angular.min.js:102) "Possibly unhandled rejection: {}"

**Comment by soulmakh** [comment]
Je n'ai pas réussi à reproduire le bug chez moi, je vais te filer une mise à jour de la base de données, et on verra ensuite si ça va résoudre le problème

**Comment by haniju** [comment]
Ok merci,
J'attends tes instructions pour le fichier sql !

**Comment by soulmakh** [comment]
Je viens de faire un push du fichier update_6.sql. A importer dans la base de données.
Il ne faut pas oublier de créer des activités (exob213) + d'en sélectionner une (exob217), avant de faire l'exercice 233

**Comment by soulmakh** [comment]
Essaie de désactiver le mode "debug" de wordpress.

> dans le fichier de MAMP : **cci/bma3/wp-config.php**  tu changes la ligne _define('WP_DEBUG', true);_ en _define('WP_DEBUG', false);_

**Comment by soulmakh** [comment]
Suite à notre dernier échange, le bug est fixé après désactivation de mode debug.
En production le mode debug est désactivé. Donc le bug ne devrai pas se produire en prod :)

**Comment by haniju** [comment]
merci :)
