### ISSUE TITLE
acces aux exercices & écrans réponses

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#19]
Il manque les url et les fichiers html/php pour les exercices suivants : 

- [x] 10.a
- [x] 10.b
- [x] 12
- [x] 14
- [x] 16
- [x] 17
- [ ] 22

**Comment by soulmakh** [comment]
[ ] B233

> 10A : http://localhost/cci/bma3/exercices/?exo_key=exob233&part=3
> 10B : http://localhost/cci/bma3/exercices/?exo_key=exob233&part=6

**Comment by soulmakh** [comment]
- [ ] exo12

> http://localhost/cci/bma3/exercices/?exo_key=exob243&part=2

**Comment by soulmakh** [comment]
- [ ] exo14

> http://localhost/cci/bma3/exercices/?exo_key=exob253&part=2

**Comment by soulmakh** [comment]
- [ ] exo16

> http://localhost/cci/bma3/exercices/?exo_key=exob266&part=2

**Comment by soulmakh** [comment]
- [ ]  Exercice 17 : http://localhost/cci/bma3/exercices/?exo_key=exoc310

**Comment by soulmakh** [comment]
pas d'exercice 22, 
dans le rapport, exo22 : _Calage d’une feuille de route_ c'est plutôt un écran de présentation
