### ISSUE TITLE
exoC511

### ISSUE THREAD

**Issue by The-MAD-Virus** [booosterdemobilite/bma-sequence-manager#22]
Salut @soulmakh,

Je tente par moi même de comprendre le fonctionnement du système, mais vue mon niveau avec AngularJS je galère trop.
peut tu m’apporter tes lumière sur exoc511.js et exoc511.php 
[https://github.com/booosterdemobilite/bma-sequence-manager/blob/exoC511/js/exos/exoc511.js](url)
[https://github.com/booosterdemobilite/bma-sequence-manager/blob/exoC511/includes/exos/exoc511.php](url)

merci,

**Comment by soulmakh** [comment]
Je viens de commiter sur ta branche une version de l'exercice C511.
Je t'ai mis le code qui marche en suivant le même raisonnement que ce que tu as opté au départ.
J'ai utilisé des questions démo (voir jeremy.sql) juste pour faire le test. A toi de mettre les bonnes questions dans la base de données pour chaque trajet

**Comment by The-MAD-Virus** [comment]
merci, je regarde tous ça lundi.
bon week-end.
