### ISSUE TITLE
Probleme d'affiche exo b216

### ISSUE THREAD

**Issue by The-MAD-Virus** [booosterdemobilite/bma-sequence-manager#30]
En parcourant le MOOC jusqu’à l'adresse suivante [http://localhost/cci/bma3/plateau/?seq=C.1.1](url) au moment du rendu du graphique, j’obtiens l'erreur suivante.
![erreur exob216](https://user-images.githubusercontent.com/9322453/31377890-de2cd1f6-ada9-11e7-990d-c2658539b803.png)

**Comment by soulmakh** [comment]
A re-tester dans la nouvelle version !
