### ISSUE TITLE
b216 - graph modifs

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#31]
- [x]  Passer les lignes noires (x & y) en gris pointillé pour les rendre plus discrètes.

- [x] Remonter les légendes colorées et les rendre plus visibles

**Comment by soulmakh** [comment]
C'est dans la nouvelle version (en cours).
J'ai aussi rajouter les rectangles en couleur pour chaque catégorie (Emergence, Déclin, Maturité et Croissance)

**Comment by soulmakh** [comment]
fait et intégré dans la nouvelle version
