### ISSUE TITLE
Ecrans réponses - templating boutons

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#4]
- [x] Systématiser le format des boutons du dessous du cadre de réponse à partir de celui de [b213] :(https://github.com/booosterdemobilite/bma-sequence-manager/commit/83c4d2dc640f859570807ce70433c7476a9c8da2#diff-bcc8f01e8afb8373b48e14efd7f8cff1)

- [x] Mettre en place le mecanisme de boutons "evolutifs" pour le cas ou il y aurait plusieurs écrans réponses successifs

**Comment by soulmakh** [comment]
Mise à jour des boutons faite pour tout les templates résultat à partir de celui de b213

**Comment by soulmakh** [comment]
Pour le deuxième point, c'set fait pour l'exo b223 (voir #7 )
