### ISSUE TITLE
exerciceApp is not defined

### ISSUE THREAD

**Issue by The-MAD-Virus** [booosterdemobilite/bma-sequence-manager#49]
J'ai un problème après la dernière mise a jour, je n'arrive plus a exécuter au qu’un exercice avec l'erreur suivant : 
![2017-10-31 12_15_08](https://user-images.githubusercontent.com/9322453/32221443-d82dc6c4-be35-11e7-811e-26e1d6662964.png)

**Comment by soulmakh** [comment]
Oui effectivement, il ne faut pas oublier de mettre à jours les templates de xpro
https://github.com/booosterdemobilite/xpro
Si les templates sont à jour tu devrais voir les exercices
Tiens moi au courant

**Comment by The-MAD-Virus** [comment]
ah ! effectivement avec les fichier que tu viens de déposer sur [https://github.com/booosterdemobilite/xpro](url) sa change tout ! ^_^
