### ISSUE TITLE
Ecran réponse de l'exercice ZERO

### ISSUE THREAD

**Issue by soulmakh** [booosterdemobilite/bma-sequence-manager#54]
J'ai créé l'exercice zéro, il ne reste que la saisie des questions et l'écran réponse
http://localhost/cci/bma3/exercices/?exo_key=intro&r=1

Pour l'instant j'ai cloné l'écran réponse de l'exercice B213

**Comment by haniju** [comment]
Le lien ne marche pas...
"unknown exo key intro"

**Comment by soulmakh** [comment]
Voici à quoi correspond la version actuelle : 
![capture d ecran 2017-11-06 a 22 04 01](https://user-images.githubusercontent.com/23297365/32463939-8d92315a-c33e-11e7-9b87-fa8cace4e0f7.png)

**Comment by soulmakh** [comment]
Je valide l'écran actuel ;)
![capture d ecran 2017-11-08 a 22 55 23](https://user-images.githubusercontent.com/23297365/32576706-fa2eec32-c4d7-11e7-99f0-e5eb13ebf6b3.png)
