### ISSUE TITLE
Graphiques à generer pour les ecrans reponses

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#6]
- [x] création de graphs "timeline" pour b223, b224, b225, b226 (références pour les inputs de donnée en b223)

**Comment by haniju** [comment]
test des graph barres en cours

**Comment by soulmakh** [comment]
- [ ] Proposition 1 [http://jsfiddle.net/soulmakh/xbzphnyt/](url)

- [ ] Proposition 2 [http://jsfiddle.net/soulmakh/tp51w83g/](url)

- [ ] Proposition 3 [http://jsfiddle.net/soulmakh/0ggae2w9/](url)

- [ ] Proposition 4 [http://jsfiddle.net/soulmakh/pfcfd7dr/](url)

**Comment by soulmakh** [comment]
Ok j'ai intégré le graphique 'Proposition 3' dans le code avec les couleurs demandées.
Si tu veux changer les couleurs c'est dans le fichier _pistes-controller-group3.js_ au niveau de la variable _$scope.highchartsColors_
