### ISSUE TITLE
Ecran réponses - affichage de plusieurs écrans successifs

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#7]
- [x] mise en place dans le templating

- [x] création d'une url pour chaque sous-page

- [x] adapter les boutons du bas

exos concernés (pour l'instant) : b223 ; b224 ; b225 ; b226 ; b233 ;

**Comment by soulmakh** [comment]
C'est fait pour le cas de b223.
Pour accéder à chaque sous page tu rajoute à l'url screen=1 (pour l'ecran 1) ou screen=2 (pour l'écran 2). Par exemple r=1&screen=1 ou r=1&screen=2
A toi de jouer ;)

**Comment by soulmakh** [comment]
C'est bon pour les exos listés (b223 ; b224 ; b225 ; b226 ; b233)
Je te laisse voir. Si c'est bon, tu peux fermer ce 'issue' #7
