### ISSUE TITLE
Ecrans réponse - ecrans à générer

### ISSUE THREAD

**Issue by haniju** [booosterdemobilite/bma-sequence-manager#9]
Edit : 
 b224 & b225 :
- [ ] screen = 1 : tableau récapitulatif à partir des 3 indicateurs (q2,3,4), et de ce modèle de [template](https://github.com/booosterdemobilite/bma-sequence-manager/blob/master/ngdir/reponses-tpl/3colones.html) 
- [ ] screen = 2 : Graphique identique à celui de b223 avec (5,6,7) à la place de (q7,8,9) (voire issue#7)

- [ ] Idem pour b226, mais en compilant toutes les pistes renseignée en b223+ b224 + b225

**Comment by soulmakh** [comment]
J'ai généré des écrans exemples pour b224 ainsi que b225 avec des inputs.
A toi de voir ;-)

**Comment by haniju** [comment]
en fait il s'agirait plutôt de générer les écrans de b224 & b225 en recopiant et automatisant ce que l'on a pour b223 - j'ai mis à jour mon premier commentaire ci-dessus avec des infos plus précises

**Comment by haniju** [comment]
J'ai préparé les fichiers pour b224 - b226 (screen 1 à chaque fois)
Reste à mettre les inputs au bons endroits, j'ai annoté le code pour les indicateurs.
